"""add unit_system to users

Revision ID: 7864a7208b84
Revises: 4dbb3249fd55
Create Date: 2026-03-26 08:28:57.012890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7864a7208b84'
down_revision: Union[str, None] = '4dbb3249fd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unit_system', sa.String(length=10), nullable=False, server_default='imperial'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unit_system')
    # ### end Alembic commands ###
