"""Sport type normalization mappings across platforms."""

# Whoop sport_id → normalized type
WHOOP_SPORT_MAP: dict[int, str] = {
    -1: "activity",
    0: "running",
    1: "cycling",
    2: "strength",
    3: "rowing",
    4: "yoga",
    5: "swimming",
    6: "hiit",
    7: "walking",
    8: "hiking",
    9: "crossfit",
    10: "tennis",
    11: "boxing",
    12: "basketball",
    13: "soccer",
    14: "martial_arts",
    15: "dance",
    16: "golf",
    17: "pilates",
    18: "surfing",
    19: "climbing",
    20: "skiing",
    21: "snowboarding",
    22: "functional_fitness",
    23: "duathlon",
    24: "triathlon",
    25: "motocross",
    26: "rugby",
    27: "cricket",
    28: "volleyball",
    29: "lacrosse",
    30: "ice_hockey",
    31: "field_hockey",
    32: "softball",
    33: "baseball",
    34: "track_and_field",
    35: "squash",
    36: "badminton",
    37: "table_tennis",
    38: "sailing",
    39: "kayaking",
    40: "water_polo",
    41: "football",
    42: "horse_riding",
    43: "meditation",
    44: "spin",
    45: "elliptical",
    46: "stairmaster",
    47: "stretching",
    48: "diving",
    49: "skateboarding",
    50: "wheelchair_pushing",
    51: "other",
    63: "obstacle_course_racing",
    64: "pickleball",
}

# Strava activity type → normalized type
STRAVA_SPORT_MAP: dict[str, str] = {
    "Run": "running",
    "Ride": "cycling",
    "Swim": "swimming",
    "Walk": "walking",
    "Hike": "hiking",
    "WeightTraining": "strength",
    "Workout": "other",
    "Yoga": "yoga",
    "CrossFit": "crossfit",
    "Rowing": "rowing",
    "Elliptical": "elliptical",
    "StairStepper": "stairmaster",
    "Kayaking": "kayaking",
    "Surfing": "surfing",
    "RockClimbing": "climbing",
    "AlpineSki": "skiing",
    "Snowboard": "snowboarding",
    "Golf": "golf",
    "Soccer": "soccer",
    "Tennis": "tennis",
    "Skateboard": "skateboarding",
    "NordicSki": "skiing",
    "IceSkate": "ice_skating",
    "Badminton": "badminton",
    "Squash": "squash",
    "TableTennis": "table_tennis",
    "Pickleball": "pickleball",
    "VirtualRide": "cycling",
    "VirtualRun": "running",
    "TrailRun": "running",
    "MountainBikeRide": "cycling",
    "GravelRide": "cycling",
    "EBikeRide": "cycling",
    "Velodrome": "cycling",
    "Sail": "sailing",
    "Canoeing": "kayaking",
    "Handcycle": "cycling",
    "Wheelchair": "wheelchair_pushing",
    "Pilates": "pilates",
    "HIIT": "hiit",
}

# Wahoo workout_type_id → normalized type (IDs may vary, update as docs clarify)
WAHOO_SPORT_MAP: dict[int, str] = {
    1: "cycling",
    12: "running",
    13: "cycling",
    24: "swimming",
    47: "strength",
    0: "other",
}


def normalize_sport_type(platform: str, raw_type: int | str) -> str:
    if platform == "whoop":
        return WHOOP_SPORT_MAP.get(int(raw_type), "other")
    elif platform == "strava":
        return STRAVA_SPORT_MAP.get(str(raw_type), "other")
    elif platform == "wahoo":
        return WAHOO_SPORT_MAP.get(int(raw_type), "other")
    return "other"
